lib.gamera_support: don't fiddle with GC if sys.getrefcount() is missing.
Fixes:

    Traceback (most recent call last):
      ...
      File ".../didjvu/lib/gamera_support.py", line 228, in init
        refcount = sys.getrefcount(test_string)
    AttributeError: 'module' object has no attribute 'getrefcount'

with PyPy.